name: flutter_riverpod_base
description: A Starter project for flutter with riverpod and http preconfigured
  in architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.5.6+10

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  app_settings: ^5.1.1
  bloc: ^8.1.4
  buffer_image: ^0.3.12
  cached_network_image: ^3.3.0
  clipboard: ^0.1.3
  country_code: ^1.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  emoji_picker_flutter: ^1.6.3
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_lifecycle_detector: ^0.0.6
  flutter_map: ^6.1.0
  flutter_rating_bar: ^4.0.1
  flutter_riverpod: null
  flutter_staggered_grid_view: ^0.7.0
  flutter_super_html_viewer: ^0.1.0
  flutter_svg: ^2.0.9
  fpdart: null
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  get_it: ^7.7.0
  go_router: ^7.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hooks_riverpod: ^2.4.9
  html_viewer_elite: ^0.0.4
  http: null
  image_picker: ^1.0.4
  intl: ^0.19.0
  jwt_decode: ^0.3.1
  liquid_pull_to_refresh: ^3.0.1
  otp_fields: ^0.0.4
  otp_timer: ^0.0.5
  photo_view: ^0.14.0
  qr_flutter: ^4.1.0
  razorpay_flutter: ^1.3.6
  rename: ^3.0.2
  rive: ^0.12.3
  riverpod: ^2.5.1
  share_plus: ^7.2.1
  shared_preferences: ^2.2.3
  shimmer_effect: ^1.0.4
  smooth_page_indicator: ^1.1.0
  socket_io_client: ^2.0.3+1
  timer_button: ^2.1.1
  upgrader: ^10.3.0
  url_launcher: ^6.2.1
  uuid: ^4.4.0
  web_socket_channel: ^2.4.4

dev_dependencies:
  change_app_package_name: ^1.2.0
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  win32: ^5.5.3

  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icons/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/placeholders/
    - assets/animations/
    - assets/icons/
